# Generated by Django 4.0.2 on 2022-02-27 09:25

from django.db import migrations, models
import exam.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_album_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[exam.main.validators.check_float_zero]),
        ),
    ]
