# Generated by Django 4.0.2 on 2022-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_profile_profile_image_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static.images.user.png', null=True, upload_to='profiles'),
        ),
    ]
