# Generated by Django 4.0.2 on 2022-02-22 10:59

import Exam_Prep_I.job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[Exam_Prep_I.job.models.MaxFileSizeInMbValidator(5)]),
        ),
    ]
